name = "CENG0038-Droplet-Distribution-research-project"
uuid = "f1629704-5882-441b-acdc-8fc8ec4ebb16"
authors = ["Ryan Sulit <zcecrjs@ucl.ac.uk> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Plots = "1.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
